import { createFileRoute } from '@tanstack/react-router'

import { ContentSection, ContentShell } from '../components/content-shell'

export const Route = createFileRoute('/terms')({
  component: TermsPage,
})

function TermsPage() {
  return (
    <ContentShell
      eyebrow="legal"
      title="Terms of Service"
      description="The terms you agree to when using Jargons. Last updated July 2026."
    >
      <ContentSection heading="Acceptance">
        <p>
          By installing the Jargons GitHub App or signing in, you agree to these
          terms. If you are using Jargons on behalf of an organization, you
          confirm you are authorized to accept these terms for it.
        </p>
      </ContentSection>

      <ContentSection heading="What Jargons does">
        <p>
          Jargons is an automated code review agent. It analyzes pull requests
          and codebases and produces findings, suggestions, and optional fix
          pull requests. These are advisory: they are generated by a large
          language model and may be incomplete or incorrect.
        </p>
      </ContentSection>

      <ContentSection heading="Your responsibilities">
        <p>
          You retain full ownership of your code. You are responsible for
          reviewing any suggestion or fix pull request before merging it. Jargons
          does not merge changes on your behalf, and you should treat its output
          as input to your own judgment, not a replacement for it.
        </p>
      </ContentSection>

      <ContentSection heading="Acceptable use">
        <p>
          Do not use Jargons to violate the law, infringe others' rights, or
          attempt to disrupt, reverse engineer, or overload the service. We may
          suspend access that threatens the reliability or security of the
          platform.
        </p>
      </ContentSection>

      <ContentSection heading="No warranty">
        <p>
          Jargons is provided “as is,” without warranties of any kind. We do not
          guarantee that reviews are accurate, complete, or that they will catch
          every issue in your code.
        </p>
      </ContentSection>

      <ContentSection heading="Limitation of liability">
        <p>
          To the fullest extent permitted by law, Jargons and its maintainers are
          not liable for any indirect, incidental, or consequential damages
          arising from your use of the service, including issues merged into your
          codebase.
        </p>
      </ContentSection>

      <ContentSection heading="Changes and termination">
        <p>
          We may update these terms or the service over time. You can stop using
          Jargons at any time by uninstalling the GitHub App. Continued use after
          a change means you accept the updated terms.
        </p>
      </ContentSection>
    </ContentShell>
  )
}
