/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as UpgradeSuccessRouteImport } from './routes/upgrade.success'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthSetupRouteImport } from './routes/auth.setup'
import { Route as AuthConnectRouteImport } from './routes/auth.connect'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScansRouteImport } from './routes/app.scans'
import { Route as AppReviewsRouteImport } from './routes/app.reviews'
import { Route as AppRepositoriesRouteImport } from './routes/app.repositories'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppScansIndexRouteImport } from './routes/app.scans.index'
import { Route as AppReviewsIndexRouteImport } from './routes/app.reviews.index'
import { Route as AppRepositoriesIndexRouteImport } from './routes/app.repositories.index'
import { Route as AuthGithubStartRouteImport } from './routes/auth.github.start'
import { Route as AuthGithubInstallRouteImport } from './routes/auth.github.install'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'
import { Route as AppScansScanIdRouteImport } from './routes/app.scans.$scanId'
import { Route as AppReviewsReviewIdRouteImport } from './routes/app.reviews.$reviewId'
import { Route as AppRepositoriesRepoIdRouteImport } from './routes/app.repositories.$repoId'
import { Route as ApiScansStartRouteImport } from './routes/api.scans.start'
import { Route as ApiGithubWebhookRouteImport } from './routes/api.github.webhook'
import { Route as ApiBillingWebhookRouteImport } from './routes/api.billing.webhook'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api.billing.checkout'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const UpgradeSuccessRoute = UpgradeSuccessRouteImport.update({
  id: '/upgrade/success',
  path: '/upgrade/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/auth/setup',
  path: '/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnectRoute = AuthConnectRouteImport.update({
  id: '/auth/connect',
  path: '/auth/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScansRoute = AppScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppScansIndexRoute = AppScansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppScansRoute,
} as any)
const AppReviewsIndexRoute = AppReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReviewsRoute,
} as any)
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRepositoriesRoute,
} as any)
const AuthGithubStartRoute = AuthGithubStartRouteImport.update({
  id: '/auth/github/start',
  path: '/auth/github/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubInstallRoute = AuthGithubInstallRouteImport.update({
  id: '/auth/github/install',
  path: '/auth/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScansScanIdRoute = AppScansScanIdRouteImport.update({
  id: '/$scanId',
  path: '/$scanId',
  getParentRoute: () => AppScansRoute,
} as any)
const AppReviewsReviewIdRoute = AppReviewsReviewIdRouteImport.update({
  id: '/$reviewId',
  path: '/$reviewId',
  getParentRoute: () => AppReviewsRoute,
} as any)
const AppRepositoriesRepoIdRoute = AppRepositoriesRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => AppRepositoriesRoute,
} as any)
const ApiScansStartRoute = ApiScansStartRouteImport.update({
  id: '/api/scans/start',
  path: '/api/scans/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/health': typeof AppHealthRoute
  '/app/repositories': typeof AppRepositoriesRouteWithChildren
  '/app/reviews': typeof AppReviewsRouteWithChildren
  '/app/scans': typeof AppScansRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/connect': typeof AuthConnectRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/app/': typeof AppIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/scans/start': typeof ApiScansStartRoute
  '/app/repositories/$repoId': typeof AppRepositoriesRepoIdRoute
  '/app/reviews/$reviewId': typeof AppReviewsReviewIdRoute
  '/app/scans/$scanId': typeof AppScansScanIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/github/install': typeof AuthGithubInstallRoute
  '/auth/github/start': typeof AuthGithubStartRoute
  '/app/repositories/': typeof AppRepositoriesIndexRoute
  '/app/reviews/': typeof AppReviewsIndexRoute
  '/app/scans/': typeof AppScansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/health': typeof AppHealthRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/connect': typeof AuthConnectRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/app': typeof AppIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/scans/start': typeof ApiScansStartRoute
  '/app/repositories/$repoId': typeof AppRepositoriesRepoIdRoute
  '/app/reviews/$reviewId': typeof AppReviewsReviewIdRoute
  '/app/scans/$scanId': typeof AppScansScanIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/github/install': typeof AuthGithubInstallRoute
  '/auth/github/start': typeof AuthGithubStartRoute
  '/app/repositories': typeof AppRepositoriesIndexRoute
  '/app/reviews': typeof AppReviewsIndexRoute
  '/app/scans': typeof AppScansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/health': typeof AppHealthRoute
  '/app/repositories': typeof AppRepositoriesRouteWithChildren
  '/app/reviews': typeof AppReviewsRouteWithChildren
  '/app/scans': typeof AppScansRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/connect': typeof AuthConnectRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/app/': typeof AppIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/scans/start': typeof ApiScansStartRoute
  '/app/repositories/$repoId': typeof AppRepositoriesRepoIdRoute
  '/app/reviews/$reviewId': typeof AppReviewsReviewIdRoute
  '/app/scans/$scanId': typeof AppScansScanIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/github/install': typeof AuthGithubInstallRoute
  '/auth/github/start': typeof AuthGithubStartRoute
  '/app/repositories/': typeof AppRepositoriesIndexRoute
  '/app/reviews/': typeof AppReviewsIndexRoute
  '/app/scans/': typeof AppScansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app/health'
    | '/app/repositories'
    | '/app/reviews'
    | '/app/scans'
    | '/app/settings'
    | '/auth/connect'
    | '/auth/setup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/upgrade/success'
    | '/app/'
    | '/api/billing/checkout'
    | '/api/billing/webhook'
    | '/api/github/webhook'
    | '/api/scans/start'
    | '/app/repositories/$repoId'
    | '/app/reviews/$reviewId'
    | '/app/scans/$scanId'
    | '/auth/github/callback'
    | '/auth/github/install'
    | '/auth/github/start'
    | '/app/repositories/'
    | '/app/reviews/'
    | '/app/scans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app/health'
    | '/app/settings'
    | '/auth/connect'
    | '/auth/setup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/upgrade/success'
    | '/app'
    | '/api/billing/checkout'
    | '/api/billing/webhook'
    | '/api/github/webhook'
    | '/api/scans/start'
    | '/app/repositories/$repoId'
    | '/app/reviews/$reviewId'
    | '/app/scans/$scanId'
    | '/auth/github/callback'
    | '/auth/github/install'
    | '/auth/github/start'
    | '/app/repositories'
    | '/app/reviews'
    | '/app/scans'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app/health'
    | '/app/repositories'
    | '/app/reviews'
    | '/app/scans'
    | '/app/settings'
    | '/auth/connect'
    | '/auth/setup'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/upgrade/success'
    | '/app/'
    | '/api/billing/checkout'
    | '/api/billing/webhook'
    | '/api/github/webhook'
    | '/api/scans/start'
    | '/app/repositories/$repoId'
    | '/app/reviews/$reviewId'
    | '/app/scans/$scanId'
    | '/auth/github/callback'
    | '/auth/github/install'
    | '/auth/github/start'
    | '/app/repositories/'
    | '/app/reviews/'
    | '/app/scans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthConnectRoute: typeof AuthConnectRoute
  AuthSetupRoute: typeof AuthSetupRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  UpgradeSuccessRoute: typeof UpgradeSuccessRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiScansStartRoute: typeof ApiScansStartRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
  AuthGithubInstallRoute: typeof AuthGithubInstallRoute
  AuthGithubStartRoute: typeof AuthGithubStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/upgrade/success': {
      id: '/upgrade/success'
      path: '/upgrade/success'
      fullPath: '/upgrade/success'
      preLoaderRoute: typeof UpgradeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/auth/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/connect': {
      id: '/auth/connect'
      path: '/auth/connect'
      fullPath: '/auth/connect'
      preLoaderRoute: typeof AuthConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scans': {
      id: '/app/scans'
      path: '/scans'
      fullPath: '/app/scans'
      preLoaderRoute: typeof AppScansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repositories': {
      id: '/app/repositories'
      path: '/repositories'
      fullPath: '/app/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scans/': {
      id: '/app/scans/'
      path: '/'
      fullPath: '/app/scans/'
      preLoaderRoute: typeof AppScansIndexRouteImport
      parentRoute: typeof AppScansRoute
    }
    '/app/reviews/': {
      id: '/app/reviews/'
      path: '/'
      fullPath: '/app/reviews/'
      preLoaderRoute: typeof AppReviewsIndexRouteImport
      parentRoute: typeof AppReviewsRoute
    }
    '/app/repositories/': {
      id: '/app/repositories/'
      path: '/'
      fullPath: '/app/repositories/'
      preLoaderRoute: typeof AppRepositoriesIndexRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
    '/auth/github/start': {
      id: '/auth/github/start'
      path: '/auth/github/start'
      fullPath: '/auth/github/start'
      preLoaderRoute: typeof AuthGithubStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/install': {
      id: '/auth/github/install'
      path: '/auth/github/install'
      fullPath: '/auth/github/install'
      preLoaderRoute: typeof AuthGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/scans/$scanId': {
      id: '/app/scans/$scanId'
      path: '/$scanId'
      fullPath: '/app/scans/$scanId'
      preLoaderRoute: typeof AppScansScanIdRouteImport
      parentRoute: typeof AppScansRoute
    }
    '/app/reviews/$reviewId': {
      id: '/app/reviews/$reviewId'
      path: '/$reviewId'
      fullPath: '/app/reviews/$reviewId'
      preLoaderRoute: typeof AppReviewsReviewIdRouteImport
      parentRoute: typeof AppReviewsRoute
    }
    '/app/repositories/$repoId': {
      id: '/app/repositories/$repoId'
      path: '/$repoId'
      fullPath: '/app/repositories/$repoId'
      preLoaderRoute: typeof AppRepositoriesRepoIdRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
    '/api/scans/start': {
      id: '/api/scans/start'
      path: '/api/scans/start'
      fullPath: '/api/scans/start'
      preLoaderRoute: typeof ApiScansStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRepositoriesRouteChildren {
  AppRepositoriesRepoIdRoute: typeof AppRepositoriesRepoIdRoute
  AppRepositoriesIndexRoute: typeof AppRepositoriesIndexRoute
}

const AppRepositoriesRouteChildren: AppRepositoriesRouteChildren = {
  AppRepositoriesRepoIdRoute: AppRepositoriesRepoIdRoute,
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
}

const AppRepositoriesRouteWithChildren = AppRepositoriesRoute._addFileChildren(
  AppRepositoriesRouteChildren,
)

interface AppReviewsRouteChildren {
  AppReviewsReviewIdRoute: typeof AppReviewsReviewIdRoute
  AppReviewsIndexRoute: typeof AppReviewsIndexRoute
}

const AppReviewsRouteChildren: AppReviewsRouteChildren = {
  AppReviewsReviewIdRoute: AppReviewsReviewIdRoute,
  AppReviewsIndexRoute: AppReviewsIndexRoute,
}

const AppReviewsRouteWithChildren = AppReviewsRoute._addFileChildren(
  AppReviewsRouteChildren,
)

interface AppScansRouteChildren {
  AppScansScanIdRoute: typeof AppScansScanIdRoute
  AppScansIndexRoute: typeof AppScansIndexRoute
}

const AppScansRouteChildren: AppScansRouteChildren = {
  AppScansScanIdRoute: AppScansScanIdRoute,
  AppScansIndexRoute: AppScansIndexRoute,
}

const AppScansRouteWithChildren = AppScansRoute._addFileChildren(
  AppScansRouteChildren,
)

interface AppRouteChildren {
  AppHealthRoute: typeof AppHealthRoute
  AppRepositoriesRoute: typeof AppRepositoriesRouteWithChildren
  AppReviewsRoute: typeof AppReviewsRouteWithChildren
  AppScansRoute: typeof AppScansRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHealthRoute: AppHealthRoute,
  AppRepositoriesRoute: AppRepositoriesRouteWithChildren,
  AppReviewsRoute: AppReviewsRouteWithChildren,
  AppScansRoute: AppScansRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthConnectRoute: AuthConnectRoute,
  AuthSetupRoute: AuthSetupRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  UpgradeSuccessRoute: UpgradeSuccessRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiScansStartRoute: ApiScansStartRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
  AuthGithubInstallRoute: AuthGithubInstallRoute,
  AuthGithubStartRoute: AuthGithubStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
